export const MockApiData = [
  {id: 1,
   destinationTitle: 'Denver',
   records_id: 1,
   images: [], 
  },
  {id: 2,
   destinationTitle: 'Aspen',
   records_id: 2,
   images: [],
  },
  {id: 3,
   destinationTitle: 'Fort Collins',
   records_id: 3,
   images: [],
  },
  {id: 4,
    destinationTitle: 'Rocky Mountain National Park',
    records_id: 4,
    images: [],
   },
]